version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: messenger
      POSTGRES_PASSWORD: messenger123
      POSTGRES_DB: messenger_db
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    ports:
      - "6379:6379"