app:
  webhook_url: "https://webhook.site/309d556c-2697-496c-9bda-5416d26b39ef"
  webhook_key: "INS.me1x9uMcyYGlhKKQVPoc.bO3j9aZwRTOcA2Ywo"
  send_interval_seconds: 120

database:
  host: "dpg-d18s7ah5pdvs73ctdj80-a.oregon-postgres.render.com"
  port: 5432
  user: "messenger_db_v5ff_user"
  password: "IrjMqhJ2NSycCbT6PT48k3FflhsDvjQa"
  name: "messenger_db_v5ff"
  sslmode: "require"

redis:
  url: "rediss://default:AaCKAAIjcDEzMDg1YmEzNjNhMjU0NWUxYTk3ZTAyYjU0Y2NjMjA0OXAxMA@guiding-lamb-41098.upstash.io:6379"
